     version: '3.8'                                                                           
                                                                                              
     services:                                                                                
       db:                                                                                    
         image: postgres:14                                                                   
         restart: always                                                                      
         environment:                                                                         
           POSTGRES_USER: your_db_user                                                        
           POSTGRES_PASSWORD: your_db_password                                                
           POSTGRES_DB: newsletter_bot                                                        
         volumes:                                                                             
           - db_data:/var/lib/postgresql/data                                                 
         ports:                                                                               
           - "5432:5432"                                                                      
                                                                                              
       bot:                                                                                   
         build: .                                                                             
         restart: always                                                                      
         env_file:                                                                            
           - .env                                                                             
         depends_on:                                                                          
           - db                                                                               
         ports:                                                                               
           - "8443:8443"                                                                      
                                                                                              
     volumes:                                                                                 
       db_data:  